commissioncalculator/protected/controllers/PasswordController.php
<?php

class PasswordController extends Controller
{

    public $layout='bootstraplayout';

	public function actionCreate()
	{
        if(Yii::app()->user->role == 'user'){
            $this->layout='bootstraplayoutuser';
        }

        $passwordModel  = new Passwordmngr();

        // Uncomment the following line if AJAX validation is needed
        //$this->performAjaxValidation($advertisementModel);

        if(isset($_POST['Passwordmngr']))
        {

            $passwordModel->attributes             = $_POST['Passwordmngr'];
            $passwordModel->user_id = Yii::app()->user->id;
            if($passwordModel->save()){

               $this->redirect(array('list'));
            }else{
                Yii::app()->user->setFlash('error', "Error creating a user record.'");
            }

        }

        // Show the details screen
        $this->render('details',array(
            'model'=>$passwordModel,
        ));


        //$this->render('details');
	}

	public function actionEdit($pid)
	{
        if(Yii::app()->user->role == 'user'){
            $this->layout='bootstraplayoutuser';
        }

        $passwordModel = Passwordmngr::model()->findByPk((int) $pid);
        if($passwordModel===null)
        {
            throw new CHttpException(404,'The requested page does not exist.');
        }

        if(isset($_POST['Passwordmngr']))
        {

            $passwordModel->attributes             = $_POST['Passwordmngr'];

            if($passwordModel->save()){

                $this->redirect(array('list'));

            }else{
                Yii::app()->user->setFlash('error', "Error creating a user record.'");
            }

        }

        // Show the details screen
        $this->render('details',array(
            'model'=>$passwordModel,
        ));
	}

    public function actionDelete(){
        $passwordid = $_POST['passwordid'];
        $passwordModel = Passwordmngr::model()->findByPk((int)$passwordid);

        if ($passwordModel == null)
        {
            header("Content-type: application/json");
            echo '{"result":"fail", "message":"Invalid User"}';
            Yii::app()->end();
        }


        $result = $passwordModel->delete();

        if ($result == false)
        {
            header("Content-type: application/json");
            echo '{"result":"fail", "message":"Failed to delete"}';
            Yii::app()->end();
        }
        else
        {
            //$this->redirect(array('index'));
        }


        echo '{"result":"success", "message":""}';
        Yii::app()->end();
    }

	public function actionIndex()
	{
        if(Yii::app()->user->role == 'user'){
            $this->layout='bootstraplayoutuser';
        }
		$this->render('index');
	}

	public function actionList()
	{
        if(Yii::app()->user->role == 'user'){
            $this->layout='bootstraplayoutuser';
        }
        $listpassword = Passwordmngr::model()->findAll('user_id='.Yii::app()->user->id);
		$this->render('list',array('listpassword'=>$listpassword));
	}


}

commissioncalculator/protected/views/password/details.php
<script type="text/javascript">
    $(document).ready(function(){
        $("ul.nav li").removeClass('active');
        $('#lipassword').addClass('active');
    });
</script>

<div class="row">
    <div class="col-sm-12">
        <div class="form">

            <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'passwordmngr-sad-form',
                'htmlOptions'=>array('class'=>'form-horizontal'),
                // Please note: When you enable ajax validation, make sure the corresponding
                // controller action is handling ajax validation correctly.
                // See class documentation of CActiveForm for details on this,
                // you need to use the performAjaxValidation()-method described there.
                'enableAjaxValidation'=>false,
            )); ?>


            <?php echo $form->errorSummary($model); ?>
            <section class="panel">
                <header class="panel-heading font-bold"><h4>User form</h4></header>
                <div class="panel-body">


                    <div class="row">
                        <div class="form-group">
                            <?php echo $form->labelEx($model,'title',array('class'=>"col-sm-2 control-label")); ?>
                            <div class="col-sm-4">
                                <?php echo $form->textField($model,'title',array('class'=>"form-control")); ?>
                                <?php echo $form->error($model,'title'); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <?php echo $form->labelEx($model,'url',array('class'=>"col-sm-2 control-label")); ?>
                            <div class="col-sm-4">
                                <?php echo $form->textField($model,'url',array('class'=>"form-control")); ?>
                                <?php echo $form->error($model,'url'); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <?php echo $form->labelEx($model,'description',array('class'=>"col-sm-2 control-label")); ?>
                            <div class="col-sm-4">
                                <?php echo $form->textField($model,'description',array('class'=>"form-control")); ?>
                                <?php echo $form->error($model,'description'); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <?php echo $form->labelEx($model,'username',array('class'=>"col-sm-2 control-label")); ?>
                            <div class="col-sm-4">
                                <?php echo $form->textField($model,'username',array('class'=>"form-control")); ?>
                                <?php echo $form->error($model,'username'); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <?php echo $form->labelEx($model,'password',array('class'=>"col-sm-2 control-label")); ?>
                            <div class="col-sm-4">
                                <?php echo $form->textField($model,'password',array('class'=>"form-control")); ?>
                                <?php echo $form->error($model,'password'); ?>
                            </div>
                        </div>
                    </div>

                </div>
            </section>

            <section class="panel">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-sm-4">
                            <button class="btn btn-white" type="submit">Cancel</button>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </div>

                </div>
            </section>

            <?php $this->endWidget(); ?>

        </div><!-- form -->
    </div>
</div>

commissioncalculator/protected/views/password/list.php
<?php
$data_url = Yii::app()->createUrl('users/listjson');
$edit_url = Yii::app()->createUrl('password/edit');
$delete_url = Yii::app()->createUrl('password/delete');
?>


<script type="text/javascript">
    $(document).ready(function(){

        $('#tbl_users').dataTable({
            "bProcessing": true,
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers"

        });

        $("ul.nav li").removeClass('active');
        $('#lipassword').addClass('active');

    });

    function deleteItem(passwordid){
        var result = window.confirm("Do you really want to Delete the user record?");
        if (result == false) {
            e.preventDefault();
            return false;
        }
        else {

            $.ajax({
                type: 'POST',
                data: { "passwordid": passwordid },
                dataType: 'json',
                url: '<?php echo CController::createURL("password/delete"); ?>',
                success: function (data) {

                    if (data.result == 'success') {
                        // Refresh the table
                        // var oTable = $('#tModuleListing').dataTable();
                        //table.draw();
                        window.location = '<?php echo CController::createURL("password/list"); ?>';
                    }
                    else {
                        alert('Failed to Delete item - ' + data.message);
                    }

                },
                error: function () {
                    alert('Failed to Delete item - unexpected error');
                    // todo: add proper error message
                }
            });
        }
    }


</script>


<section class="panel">
    <header class="panel-heading">
        <h4>Passwords &nbsp;&nbsp;<a id="add" name="add" href="<?php echo Yii::app()->createUrl('password/create'); ?>" class="btn btn-success btn-sm"><i class="fa fa-plus"></i></a></h4>
    </header>
    <div class="table-responsive">
        <table id="tbl_users" class="table table-striped m-b-none">
            <thead>
            <tr>
                <th width="30%">Title</th>
                <th width="30%">Description</th>
                <th width="10%">&nbsp;</th>
                <th width="10%">&nbsp;</th>
            </tr>
            </thead>

            <?php
            if(count($listpassword>0)){
                echo '<tbody>';
                foreach($listpassword as $password){
                    echo '<tr>';
                    echo '<td><a href="http://'.$password->url.'" target="_blank">'.$password->title.'</a></td>';
                    echo '<td>'.$password->description.'</td>';
                    echo '<td><a class="editrow btn btn-info btn-xs" href="'.$edit_url.'/pid/'.$password->id.'">Edit</a></td>';
                    echo '<td><a href="javascript:void(0);" onclick="deleteItem('.$password->id.');" class="deleterow btn btn-danger btn-xs">Delete</a></td>';
                    echo '</tr>';
                }
                echo '</tbody>';
            }
            ?>


        </table>
    </div>
</section>