commissioncalculator/protected/models/Users.php
<?php

/**
 * This is the model class for table "{{users}}".
 *
 * The followings are the available columns in table '{{users}}':
 * @property integer $userid
 * @property string $firstname
 * @property string $lastname
 * @property string $reeanumber
 * @property string $irdnumber
 * @property string $companyname
 * @property string $companyemail
 * @property string $personalemail
 * @property string $mobilephonenumber
 * @property double $usershare
 * @property double $payepercentage
 * @property double $withholdingtax
 * @property string $createdtime
 * @property string $modifiedtime
 * @property integer $createdby
 * @property integer $modifiedby
 * @property integer $isactive
 */
class Users extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{users}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
            array('firstname, lastname', 'required'),
			array('createdby, modifiedby', 'numerical', 'integerOnly'=>true),
			array('usershare, payepercentage, withholdingtax', 'numerical'),
			array('firstname, lastname, reeanumber, irdnumber', 'length', 'max'=>36),
			array('companyname, companyemail, personalemail', 'length', 'max'=>100),
			array('mobilephonenumber', 'length', 'max'=>50),
			array('createdtime', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('userid, firstname, lastname, reeanumber, irdnumber, companyname, companyemail, personalemail, mobilephonenumber, usershare, payepercentage, withholdingtax, createdtime, modifiedtime, createdby, modifiedby,isactive', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'bonusdeductions' => array(self::HAS_MANY, 'Bonusdeductions', 'userid'),
			'managers' => array(self::HAS_MANY, 'Managers', 'usertomanage'),
			'transactions' => array(self::HAS_MANY, 'Transaction', 'modifiedby'),
			'transactionreports' => array(self::HAS_MANY, 'Transactionreport', 'modifiedbyid'),
			'useraccounts' => array(self::HAS_MANY, 'Useraccounts', 'userid'),
			'createdby0' => array(self::BELONGS_TO, 'Users', 'createdby'),
			'users' => array(self::HAS_MANY, 'Users', 'modifiedby'),
			'modifiedby0' => array(self::BELONGS_TO, 'Users', 'modifiedby'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'userid' => 'Userid',
			'firstname' => 'Firstname',
			'lastname' => 'Lastname',
			'reeanumber' => 'Reeanumber',
			'irdnumber' => 'Irdnumber',
			'companyname' => 'Companyname',
			'companyemail' => 'Companyemail',
			'personalemail' => 'Personalemail',
			'mobilephonenumber' => 'Mobilephonenumber',
			'usershare' => 'Usershare',
			'payepercentage' => 'Payepercentage',
			'withholdingtax' => 'Withholdingtax',
			'createdtime' => 'Createdtime',
			'modifiedtime' => 'Modifiedtime',
			'createdby' => 'Createdby',
			'modifiedby' => 'Modifiedby',
            'isactive' => 'Isactive',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('userid',$this->userid);

		$criteria->compare('firstname',$this->firstname,true);

		$criteria->compare('lastname',$this->lastname,true);

		$criteria->compare('reeanumber',$this->reeanumber,true);

		$criteria->compare('irdnumber',$this->irdnumber,true);

		$criteria->compare('companyname',$this->companyname,true);

		$criteria->compare('companyemail',$this->companyemail,true);

		$criteria->compare('personalemail',$this->personalemail,true);

		$criteria->compare('mobilephonenumber',$this->mobilephonenumber,true);

		$criteria->compare('usershare',$this->usershare);

		$criteria->compare('payepercentage',$this->payepercentage);

		$criteria->compare('withholdingtax',$this->withholdingtax);

		$criteria->compare('createdtime',$this->createdtime,true);

		$criteria->compare('modifiedtime',$this->modifiedtime,true);

		$criteria->compare('createdby',$this->createdby);

		$criteria->compare('modifiedby',$this->modifiedby);

        $criteria->compare('isactive',$this->isactive);

		return new CActiveDataProvider('Users', array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * @return Users the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}



    public function beforeSave() {

        // /////////////////////////////////////////////////////////////////
        // Set the create time and user for new records
        // /////////////////////////////////////////////////////////////////
        if ($this->isNewRecord) {
            $this->createdtime = new CDbExpression('NOW()');
            //$this->created_by   = Yii::app()->user->id;
        }

        // /////////////////////////////////////////////////////////////////
        // The modified log details is set for record creation and update
        // /////////////////////////////////////////////////////////////////
        $this->modifiedtime = new CDbExpression('NOW()');
        //$this->modified_by   = Yii::app()->user->id;


        return parent::beforeSave();
    }

    public function getFullName(){
        return $this->firstname . ' ' . $this->lastname;
    }
}

commissioncalculator/protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{

    public $layout='bootstraplayout';

    public function actionCreate()
    {
        $usersModel  = new Users();

        // Uncomment the following line if AJAX validation is needed
        //$this->performAjaxValidation($advertisementModel);

        if(isset($_POST['Users']))
        {

            $usersModel->attributes             = $_POST['Users'];

            if($usersModel->save()){

                $userAccnt = new Useraccounts();
                $userAccnt->userid = $usersModel->userid;
                $userAccnt->username =  $usersModel->personalemail;
                $userAccnt->password = 'jameslaw';

                $userAccnt->save();

                $this->redirect(array('index'));
            }else{

                Yii::app()->user->setFlash('error', "Error creating a user record.'");
            }

        }

        // Show the details screen
        $this->render('details',array(
            'model'=>$usersModel,
        ));


        //$this->render('details');
    }

    public function actionEdit($userid)
    {

        if(Yii::app()->user->role == 'user'){
            $this->layout='bootstraplayoutuser';
        }

        $usersModel = Users::model()->findByPk((int) $userid);
        if($usersModel===null)
        {
            throw new CHttpException(404,'The requested page does not exist.');
        }

        if(isset($_POST['Users']))
        {

            $usersModel->attributes             = $_POST['Users'];

            if($usersModel->save()){

                if(Yii::app()->user->role == 'user'){
                    $this->redirect(array('users/edit/userid/' . $usersModel->usserid));
                }else{
                    $this->redirect(array('index'));
                }

            }else{
                Yii::app()->user->setFlash('error', "Error creating a user record.'");
            }

        }

        // Show the details screen
        $this->render('details',array(
            'model'=>$usersModel,
        ));
    }

    public function actionDelete()
    {
        $userid = $_POST['userid'];

        //echo $_POST['userid'];
        $usersModel = Users::model()->findByPk((int)$userid);
        //$usersModel = new Users();
        $usersModel->isactive=0;

        if ($usersModel == null)
        {
            header("Content-type: application/json");
            echo '{"result":"fail", "message":"Invalid User"}';
            Yii::app()->end();
        }

        $result = $usersModel->save();

        if ($result == false)
        {
            header("Content-type: application/json");
            echo '{"result":"fail", "message":"Failed to mark record for deletion"}';
            Yii::app()->end();
        }
        else
        {
            //$this->redirect(array('index'));
        }

        echo '{"result":"success", "message":""}';
        Yii::app()->end();

    }

    public function actionIndex()
    {
        $listUsers          = Users::model()->findAll('isactive=1');
        $this->render('list',array('listUsers'=>$listUsers));
    }

    public function actionList()
    {
        $this->render('list');
    }

    public function actionListjson() {

        // /////////////////////////////////////////////////////////////////////
        // Create a Db Criteria to filter and customise the resulting results
        // /////////////////////////////////////////////////////////////////////
        $searchCriteria = new CDbCriteria;

        // Paging criteria
        // Set defaults
        $limitStart 	           = isset($_POST['start'])?$_POST['start']:0;
        $limitItems 	           = isset($_POST['length'])?$_POST['length']:Yii::app()->params['PAGESIZEREC'];

        $searchCriteria->limit 		 = $limitItems;
        $searchCriteria->offset 	 = $limitStart;

        $listUsers          = Users::model()->findAll($searchCriteria);


        $countRows 		            = Users::model()->count($searchCriteria);;
        $countTotalRecords 		    = Users::model()->count();

        /*
         * Output
         */
        $resultsAdvertTable = array(
            "iTotalRecords"         => $countRows,
            "iTotalDisplayRecords"  => $countTotalRecords,
            "aaData"                => array()
        );

        foreach($listUsers as $item){

            $fullname = $item->attributes['firstname'] . ' ' . $item->attributes['lastname'];

            $rowResult = array(
                $fullname,
                $item->attributes['reeanumber'],
                $item->attributes['irdnumber'],
                $item->attributes['companyname'],
                ''
            );

            $resultsAdvertTable['aaData'][] = $rowResult;

        }

        echo json_encode($resultsAdvertTable);
        //echo CJSON::encode($resultsAdvertTable);
        Yii::app()->end();

}

    public function actionUseraccountslist() {
        $listUseraccounts         = Useraccounts::model()->findAll();
        $this->render('useraccountlist',array('listUseraccounts'=>$listUseraccounts));
    }

    public function actionEdituseraccounts($useraccountsid){
        //echo 'ss';die();

        $userAccount = Useraccounts::model()->findByPk((int) $useraccountsid);
        if($userAccount===null)
        {
            throw new CHttpException(404,'The requested page does not exist.');
        }

        if(isset($_POST['Useraccounts']))
        {
            $userAccount->attributes           = $_POST['Useraccounts'];

            if($userAccount->save()){
                $this->redirect(array('useraccountslist'));
            }else{
                Yii::app()->user->setFlash('error', "Error creating a user record.'");
            }
        }

        // Show the details screen
        $this->render('useraccountdetails',array(
            'model'=>$userAccount,
        ));
    }

    public function actionBonusdeductionlist() {
        $listBonusdeduction       = Bonusdeductions::model()->findAll();
        $this->render('bonusdeductionlist',array('listBonusdeduction'=>$listBonusdeduction));
    }

    public function actionCreatebonusdeduction(){
        $bonusdeductionModel  = new Bonusdeductions();

        // Uncomment the following line if AJAX validation is needed
        //$this->performAjaxValidation($advertisementModel);

        if(isset($_POST['Bonusdeductions']))
        {
            //print_r( $_POST['Bonusdeductions']);die();
            $bonusdeductionModel = Bonusdeductions::model()->find('userid=' . $_POST['Bonusdeductions']['userid']);
            if(!empty($bonusdeductionModel)){
                $bonusdeductionModel->amount = $bonusdeductionModel->amount + $_POST['Bonusdeductions']['amount'];
                $bonusdeductionModel->description = $_POST['Bonusdeductions']['description'];
                $bonusdeductionModel->gst = $_POST['Bonusdeductions']['gst'];
                if($bonusdeductionModel->save()){

                    $bonusline = new Bonusdeductionsline();
                    $bonusline->amount = $_POST['Bonusdeductions']['amount'];
                    $bonusline->bonusdeductionsid = $bonusdeductionModel->bonusdeductionid;
                    $bonusline->description = $_POST['Bonusdeductions']['description'];
                    $bonusline->gst = $_POST['Bonusdeductions']['gst'];

                    $start_date = $_POST['txtDate'];
                    $start_date = strtotime($start_date);
                    $start_date = date("Y/m/d", $start_date);
                    $bonusline->createdtime = $start_date;

                    $bonusline->save();
                    $this->redirect(array('bonusdeductionlist'));
                }else{
                    Yii::app()->user->setFlash('error', "Error creating a user record.'");
                }
            }else{

                //print_r($_POST['Bonusdeductions']);die();
                $bonusdeductionModel1 = new Bonusdeductions();
                $bonusdeductionModel1->amount = $_POST['Bonusdeductions']['amount'];
                $bonusdeductionModel1->description = $_POST['Bonusdeductions']['descri[tion'];
                $bonusdeductionModel1->userid = $_POST['Bonusdeductions']['userid'];
                $bonusdeductionModel1->gst = $_POST['Bonusdeductions']['gst'];
                if($bonusdeductionModel1->save()){

                    $bonusline = new Bonusdeductionsline();
                    $bonusline->amount = $_POST['Bonusdeductions']['amount'];
                    $bonusline->bonusdeductionsid = $bonusdeductionModel1->bonusdeductionid;
                    $bonusline->description = $_POST['Bonusdeductions']['description'];
                    $bonusline->gst = $_POST['Bonusdeductions']['gst'];

                    $start_date = $_POST['txtDate'];
                    $start_date = strtotime($start_date);
                    $start_date = date("Y/m/d", $start_date);
                    $bonusline->createdtime = $start_date;

                    if(!$bonusline->save()){
                        print_r($bonusline->getErrors());die();
                    }else{
                        $this->redirect(array('bonusdeductionlist'));
                    }

                }else{
                    Yii::app()->user->setFlash('error', "Error creating a user record.'");
                }
            }

        }
        $userid = '';
        if(isset($_GET['uid'])){
            $userid = $_GET['uid'];

        }
        $this->render('bonusdeductiondetails',array(
            'model'=>$bonusdeductionModel,'userid'=>$userid
        ));

    }

    public function actionViewbonusdeduction($bonusdeductionid){
        $bonusdeductionModel = Bonusdeductions::model()->findByPk((int) $bonusdeductionid);

        $this->render('bonusdeductionview',array(
            'model'=>$bonusdeductionModel,
        ));

    }

    public function actionEditbonusdeduction($bonusdeductionid){

commissioncalculator/protected/views/users/bonusdeductionlist.php
<?php
$data_url = Yii::app()->createUrl('users/listjson');
$edit_url = Yii::app()->createUrl('users/viewbonusdeduction');
$delete_url = Yii::app()->createUrl('users/deletebonusdeduction');
?>


<script type="text/javascript">
    $(document).ready(function(){

        $('#tbl_users').dataTable({
            "bProcessing": true,
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers",

        });

        $("ul.nav li").removeClass('active');
        $('#liuser').addClass('active');

    });

    function deleteItem(bonusdeductionid){
        var result = window.confirm("Do you really want to Delete the user record?");
        if (result == false) {
            e.preventDefault();
            return false;
        }
        else {

            $.ajax({
                type: 'POST',
                data: { "bonusdeductionid": bonusdeductionid },
                dataType: 'json',
                url: '<?php echo CController::createURL("users/deletebonusdeduction"); ?>',
                success: function (data) {

                    if (data.result == 'success') {
                        // Refresh the table
                        // var oTable = $('#tModuleListing').dataTable();
                        //table.draw();
                        window.location = '<?php echo CController::createURL("users/bonusdeductionlist"); ?>';
                    }
                    else {
                        alert('Failed to Delete item - ' + data.message);
                    }

                },
                error: function () {
                    alert('Failed to Delete item - unexpected error');
                    // todo: add proper error message
                }
            });
        }
    }


</script>


<section class="panel">
    <header class="panel-heading">
        <h4>Bonus And Deduction List &nbsp;&nbsp;<a id="add" name="add" href="<?php echo Yii::app()->createUrl('users/createbonusdeduction'); ?>" class="btn btn-success btn-sm"><i class="fa fa-plus"></i></a></h4>
    </header>
    <div class="table-responsive">
        <table id="tbl_users" class="table table-striped m-b-none">
            <thead>
            <tr>
                <th width="15%">User</th>
                <th width="15%">Amount</th>
                <th width="35%">Description</th>
                <th width="15%">GST</th>
                <th width="10%">&nbsp;</th>
                <th width="10%">&nbsp;</th>
            </tr>
            </thead>

            <?php
            if(count($listBonusdeduction>0)){
                echo '<tbody>';
                foreach($listBonusdeduction as $bonusdeduction){
                    echo '<tr>';
                    echo '<td>'.$bonusdeduction->user->firstname. ' ' . $bonusdeduction->user->lastname.'</td>';
                    echo '<td>'.$bonusdeduction->amount.'</td>';
                    echo '<td>'.$bonusdeduction->description.'</td>';
                    echo '<td>'.$bonusdeduction->gst.'</td>';
                    echo '<td><a class="editrow btn btn-info btn-xs" href="'.$edit_url.'/bonusdeductionid/'.$bonusdeduction->bonusdeductionid.'">View Details</a></td>';
                    echo '<td><a href="javascript:void(0);" onclick="deleteItem('.$bonusdeduction->bonusdeductionid.');" class="deleterow btn btn-danger btn-xs">Delete</a></td>';
                    echo '</tr>';
                }
                echo '</tbody>';
            }
            ?>


        </table>
    </div>
</section>

commissioncalculator/protected/views/users/bonusdeductionview.php
<script type="text/javascript">
    $(document).ready(function(){

        $('#tbl_bonus').dataTable({
            "bProcessing": true,
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers"

        });

        $("ul.nav li").removeClass('active');
        $('#liuser').addClass('active');

    });
 </script>

<div class="row">
    <div class="col-sm-12">

        <?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'bonusdeductions-asd-form',
            'htmlOptions'=>array('class'=>'form-horizontal'),
            // Please note: When you enable ajax validation, make sure the corresponding
            // controller action is handling ajax validation correctly.
            // See class documentation of CActiveForm for details on this,
            // you need to use the performAjaxValidation()-method described there.
            'enableAjaxValidation'=>false,
        )); ?>

        <section class="panel">
            <header class="panel-heading font-bold"><h4>Bonus and Deductions for <?php echo $model->user->fullname;?> &nbsp;&nbsp;<a id="add" name="add" href="<?php echo Yii::app()->createUrl('users/createbonusdeduction',array('uid'=>$model->userid)); ?>" class="btn btn-success btn-sm">Add Bonus/Deduction</a></h4></header>
            <div class="panel-body">

                <div class="form-group">
                    <label class="col-sm-4 control-label" style="text-align: left !important;">Total Bonus Amount : <?php echo $model->amount; ?></label>


                    <label class="col-sm-4 control-label"  style="text-align: left !important;">Description : <?php echo $model->description; ?></label>

                    <label class="col-sm-4 control-label"  style="text-align: left !important;">GST : <?php echo $model->gst; ?></label>
                </div>
                <div class="line line-dashed line-lg pull-in"></div>

            </div>

            <header class="panel-heading font-bold"><h4>Details</h4></header>
            <div class="panel-body">

                <table id="tbl_bonus" class="table table-striped m-b-none">
                    <thead>
                    <tr>
                        <th width="15%">Date</th>
                        <th width="15%">Amount</th>
                        <th width="35%">Description</th>
                        <th width="15%">GST</th>
                    </tr>
                    </thead>

                    <?php


                    if(count($model->bonusdeductionslines>0)){
                        echo '<tbody>';
                        foreach($model->bonusdeductionslines as $bonusdeduction){
                            echo '<tr>';
                            echo '<td>'.date('d/m/Y',strtotime($bonusdeduction->createdtime)).'</td>';
                            echo '<td>'.$bonusdeduction->amount.'</td>';
                            echo '<td>'.$bonusdeduction->description.'</td>';
                            echo '<td>'.$bonusdeduction->gst.'</td>';
                            echo '</tr>';
                        }
                        echo '</tbody>';
                    }
                    ?>


                </table>

            </div>
        </section>



        <section class="panel" style="display:none;">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-4">
                        <button class="btn btn-white" type="submit">Cancel</button>
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </div>
                </div>

            </div>
        </section>

        <?php $this->endWidget(); ?>

    </div>

</div>

<script type="text/javascript">

</script>

commissioncalculator/protected/views/users/list.php
<?php
    $data_url = Yii::app()->createUrl('users/listjson');
    $edit_url = Yii::app()->createUrl('users/edit');
    $delete_url = Yii::app()->createUrl('users/delete');
?>


<script type="text/javascript">
    $(document).ready(function(){

        $('#tbl_users').dataTable({
            "bProcessing": true,
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers",

        });

    });

    function deleteItem(userid){
        var result = window.confirm("Do you really want to Delete the user record?");
        if (result == false) {
            e.preventDefault();
            return false;
        }
        else {

            $.ajax({
                type: 'POST',
                data: { "userid": userid },
                dataType: 'json',
                url: '<?php echo CController::createURL("users/delete"); ?>',
                success: function (data) {

                    if (data.result == 'success') {
                        // Refresh the table
                        // var oTable = $('#tModuleListing').dataTable();
                        //table.draw();
                        window.location = '<?php echo CController::createURL("users/index"); ?>';
                    }
                    else {
                        alert('Failed to Delete item - ' + data.message);
                    }

                },
                error: function () {
                    alert('Failed to Delete item - unexpected error');
                    // todo: add proper error message
                }
            });
        }
    }


</script>


<section class="panel">
    <header class="panel-heading">
        <h4>Users List &nbsp;&nbsp;<a id="add" name="add" href="<?php echo Yii::app()->createUrl('users/create'); ?>" class="btn btn-success btn-sm"><i class="fa fa-plus"></i></a></h4>
    </header>
    <div class="table-responsive">
        <table id="tbl_users" class="table table-striped m-b-none">
            <thead>
            <tr>
                <th width="20%">Name</th>
                <th width="15%">REAA number</th>
                <th width="15%">IRD Number</th>
                <th width="20%"> Company Name</th>
                <th width="15%">&nbsp;</th>
                <th width="15%">&nbsp;</th>
            </tr>
            </thead>

            <?php
                if(count($listUsers>0)){
                    echo '<tbody>';
                    foreach($listUsers as $user){
                        echo '<tr>';
                        echo '<td>'.$user->firstname. ' ' . $user->lastname.'</td>';
                        echo '<td>'.$user->reeanumber.'</td>';
                        echo '<td>'.$user->irdnumber.'</td>';
                        echo '<td>'.$user->companyname.'</td>';
                        echo '<td><a class="editrow btn btn-info btn-xs" href="'.$edit_url.'/userid/'.$user->userid.'">Edit</a></td>';
                        echo '<td><a href="javascript:void(0);" onclick="deleteItem('.$user->userid.');" class="deleterow btn btn-danger btn-xs">Delete</a></td>';
                        echo '</tr>';
                    }
                    echo '</tbody>';
                }
            ?>


        </table>
    </div>
</section>

commissioncalculator/protected/views/users/useraccountlist.php
<?php
    $edit_url = Yii::app()->createUrl('users/edituseraccounts');
?>


<script type="text/javascript">
    $(document).ready(function(){

        $('#tbl_users').dataTable({
            "bProcessing": true,
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers",

        });

        $("ul.nav li").removeClass('active');
        $('#liuser').addClass('active');

    });

    function deleteItem(userid){
        var result = window.confirm("Do you really want to Delete the user record?");
        if (result == false) {
            e.preventDefault();
            return false;
        }
        else {

            $.ajax({
                type: 'POST',
                data: { "userid": userid },
                dataType: 'json',
                url: '<?php echo CController::createURL("users/delete"); ?>',
                success: function (data) {

                    if (data.result == 'success') {
                        // Refresh the table
                        // var oTable = $('#tModuleListing').dataTable();
                        //table.draw();
                        window.location = '<?php echo CController::createURL("users/index"); ?>';
                    }
                    else {
                        alert('Failed to Delete item - ' + data.message);
                    }

                },
                error: function () {
                    alert('Failed to Delete item - unexpected error');
                    // todo: add proper error message
                }
            });
        }
    }


</script>


<section class="panel">
    <header class="panel-heading">
        <h4>Users List &nbsp;&nbsp;<a id="add" style="display:none;" name="add" href="<?php echo Yii::app()->createUrl('users/create'); ?>" class="btn btn-success btn-sm"><i class="fa fa-plus"></i></a></h4>
    </header>
    <div class="table-responsive">
        <table id="tbl_users" class="table table-striped m-b-none">
            <thead>
            <tr>
                <th width="20%">Name</th>
                <th width="15%">Username</th>
                <th width="15%">Account Type</th>
                <th width="15%">&nbsp;</th>
            </tr>
            </thead>

            <?php
            if(count($listUseraccounts>0)){
                echo '<tbody>';
                foreach($listUseraccounts as $accounts){
                    echo '<tr>';
                    echo '<td>'.$accounts->user->firstname. ' ' . $accounts->user->lastname.'</td>';
                    echo '<td>'.$accounts->username.'</td>';
                    echo '<td>'.$accounts->accounttype.'</td>';
                    echo '<td><a class="editrow btn btn-info btn-xs" href="'.$edit_url.'/useraccountsid/'.$accounts->useraccountsid.'">Edit</a></td>';

                    echo '</tr>';
                }
                echo '</tbody>';
            }
            ?>


        </table>
    </div>
</section>